config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'

  resources :users
  resources :histories, only: [:index, :show]
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/histories/edit_name.rb
class Histories::EditName < History
end

app/models/histories/fire.rb
class Histories::Fire < History

end

app/models/histories/hire.rb
class Histories::Hire < History

end

app/models/histories/transfer.rb
class Histories::Transfer < History

end

app/models/history.rb
class History < ActiveRecord::Base
  belongs_to :user

  def type_name
    type_underscore = self.class.name.demodulize.underscore
    text = I18n.t("histories.active_record.type.#{type_underscore}")
    "<span class=\"#{type_underscore}\">#{text}</span>".html_safe
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :department
end

app/models/user.rb
class User < ActiveRecord::Base
  EDIT_ACTIONS = %w(transfer edit_name fire)

  belongs_to :department
  belongs_to :position
  has_many :histories

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :department, presence: true
  validates :position, presence: true

  after_create :create_fire_history
  after_initialize :set_defaults

  private

  def create_fire_history
    Histories::Hire.create(user_id: self.id, date: Date.today)
  end

  def set_defaults
    self.fired ||= false
    self.hr_manager ||= false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  def index
    @histories = History.all
  end

  def show
  end

  # # GET /histories/new
  # def new
  #   @history = History.new
  # end
  #
  # # GET /histories/1/edit
  # def edit
  # end
  #
  # # POST /histories
  # # POST /histories.json
  # def create
  #   @history = History.new(history_params)
  #
  #   respond_to do |format|
  #     if @history.save
  #       format.html { redirect_to @history, notice: 'History was successfully created.' }
  #       format.json { render :show, status: :created, location: @history }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @history.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # # PATCH/PUT /histories/1
  # # PATCH/PUT /histories/1.json
  # def update
  #   respond_to do |format|
  #     if @history.update(history_params)
  #       format.html { redirect_to @history, notice: 'History was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @history }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @history.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  #
  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end
  #
  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def history_params
  #     params.require(:history).permit(:user_id, :type, :attribute_name, :old_value, :new_value, :date)
  #   end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_action_name, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user_form = UserFormFactoryService.new(@user, @action_name).user_form
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user_form = UserFormFactoryService.new(@user, user_params[:action_name]).user_form

    respond_to do |format|
      if @user_form.submit(user_params.except(:action_name))
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :department_id, :position_id, :salary, :fired, :hr_manager, :action_name, :reason)
    end

    def set_action_name
      action_name = params[:action_name]
      action_name ||= user_params[:action_name] if params[:user]
      @action_name = User::EDIT_ACTIONS.include?(action_name) ? action_name : nil
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/histories/_form.html.slim
= form_for @history do |f|
  - if @history.errors.any?
    #error_explanation
      h2 = "#{pluralize(@history.errors.count, "error")} prohibited this history from being saved:"
      ul
        - @history.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :attribute_name
    = f.text_field :attribute_name
  .field
    = f.label :old_value
    = f.text_field :old_value
  .field
    = f.label :new_value
    = f.text_field :new_value
  .field
    = f.label :date
    = f.date_select :date
  .actions = f.submit

app/views/histories/edit.html.slim
h1 Editing history

== render 'form'

= link_to 'Show', @history
'|
= link_to 'Back', histories_path

app/views/histories/index.html.slim
h1 Listing histories

table.table.table-stripped
  thead
    tr
      th User ID
      th Type
      th Attribute name
      th Old value
      th New value string
      th Date
      th
      th

  tbody
    - @histories.each do |history|
      tr
        td = history.user_id
        td = history.type_name
        td = history.attribute_name
        td = history.old_value
        td = history.new_value
        td = I18n.l(history.date, format: '%d.%m.%Y')
        td = link_to 'Show', history_path(history)
        td = link_to 'Destroy', history_path(history), data: { confirm: 'Are you sure?' }, method: :delete

br

app/views/histories/new.html.slim
h1 New history

== render 'form'

= link_to 'Back', histories_path

app/views/histories/show.html.slim
p#notice = notice

p
  strong User:
  = @history.user_id
p
  strong Type:
  = @history.type
p
  strong Attribute name:
  = @history.attribute_name
p
  strong Old value:
  = @history.old_value
p
  strong New value string:
  = @history.new_value
p
  strong Date:
  = @history.date

= link_to 'Back', histories_path

app/views/layouts/application.html.slim
doctype html
html lang="en" 
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta charset="utf-8" /
    meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title= content_for?(:title) ? yield(:title) : "Sqhr"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    /! For third-generation iPad with high-resolution Retina display:
    /! Size should be 144 x 144 pixels
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    /! For iPhone with high-resolution Retina display:
    /! Size should be 114 x 114 pixels
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    /! For first- and second-generation iPad:
    /! Size should be 72 x 72 pixels
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    /! For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
    /! Size should be 57 x 57 pixels
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /! For all other devices
    /! Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  /! Le HTML5 shim, for IE6-8 support of HTML elements
  /![if lt IE 9]
      | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script
  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button" 
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#"  Sqhr
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to 'Создать пользователя', new_user_path
            li= link_to 'Список пользователей', users_path
            li= link_to 'Действия над пользователями', histories_path
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
      /! /.well
      /! /span
      /! /row
      footer
        p © Company 2016
          /! /container

app/views/main/index.html.slim
h1
  | Добро пожаловать на SQHR
p
  | Для навигации по сайту воспользуйтесь навигацией, расположенной наверху.

app/views/users/_form.html.slim
= simple_form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  = f.input :first_name
  = f.input :last_name
  = f.input :department_id, as: :select, collection: Department.all, label_method: :name, value_method: :id
  = f.input :position_id, as: :select, collection: Position.all, label_method: :name, value_method: :id
  = f.input :salary
  hr
  = f.submit

app/views/users/_show.html.slim
p
  strong First name:
  = @user.first_name
p
  strong Last name:
  = @user.last_name
p
  strong Department:
  = @user.department.name
p
  strong Position:
  = @user.position.name
p
  strong Salary:
  = @user.salary
p
  strong fired:
  = @user.fired
p
  strong Hr manager:
  = @user.hr_manager

app/views/users/edit.html.slim
h1 Editing user

- if @action_name
  = render partial: 'show'
  hr
  = simple_form_for @user_form do |f|
    = f.input :action_name, as: :hidden, input_html: { value: @action_name }
    = render partial: "users/edit_forms/#{@action_name}", locals: { f: f }
- else
  - if @user.fired?
    h3
      | Пользователь уволен
  - else
    = render partial: 'users/edit_forms/choose_action_name'
= link_to 'Back', users_path

app/views/users/edit_forms/_choose_action_name.html.slim
h3
  | Выберите действие.
ul
  - User::EDIT_ACTIONS.each do |action_name|
    li
      = link_to t("users.actions.#{action_name}"), edit_user_path(action_name: action_name)

app/views/users/edit_forms/_edit_name.html.slim
= f.input :first_name
= f.input :last_name
= f.submit 'Поменять имя и фамилию'

app/views/users/edit_forms/_fire.html.slim
= f.input :reason, as: :text
= f.input :fired, as: :hidden, input_html: { value: true }
= f.submit 'Уволить'

app/views/users/edit_forms/_transfer.html.slim
= f.input :department_id, as: :select, collection: Department.all, lavel_method: :name, value_method: :id
= f.input :position_id, as: :select, collection: Position.all, lavel_method: :name, value_method: :id
= f.input :salary
= f.submit 'Перевести'

app/views/users/index.html.slim
h1 Listing users

table.table.table-stripped
  thead
    tr
      th First name
      th Last name
      th Department
      th Position
      th Salary
      th fired
      th Hr manager
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.first_name
        td = user.last_name
        td = user.department.name
        td = user.position.name
        td = user.salary
        td = user.fired
        td = user.hr_manager
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

= render partial: 'show'

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path